---
name: SVN-Notify-Filter-Markdown
version: 0.03
author:
  - 'David E. Wheeler <david@kineticode.com>'
abstract: Convert SVN::Notify log messages from Markdown to HTML
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  HTML::Entities: 0
  SVN::Notify: 2.70
  Text::Markdown: 0
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
provides:
  SVN::Notify::Filter::Markdown:
    file: lib/SVN/Notify/Filter/Markdown.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
